.prettierrc.js, package.json, pnpm-lock.yaml, src/App.tsx, src/main.tsx, src/routes/index.tsx, src/style/GlobalStyles.tsx, src/style/theme.ts
첫번째 PR!
refer #1
theme.ts 에 TODO를 남겨두었습니다.
각자 확인하시고 분업하시기 바랍니다!
기한 (04/03 수요일까지)
=> feat: 초기 코드 및 스타일 초기화

package.json, pnpm-lock.yaml, src/components/ProductForm/AddProductForm.tsx, src/components/ProductForm/MentoringQuestionForm.tsx, src/components/ProductForm/MentoringQuestionList.tsx, src/components/ProductForm/MentoringSelect.tsx, src/components/ProductForm/ProductFormInput.tsx, src/components/ProductForm/ProductFormSelect.tsx, src/components/ProductForm/ProductItem.tsx, src/components/ProductForm/ProductList.tsx, src/hooks/ProductForm/useMentoring.ts, src/hooks/ProductForm/useProductForm.ts, src/hooks/ProductForm/useProducts.ts, src/hooks/ProductForm/useRegisterProduct.ts, src/pages/ProductFormPage.tsx
- 사용하는 비즈니스 로직을 추가하였습니다.
- 추후 api 연동이 편리하도록 세팅해두었습니다.
=> feat: 기자재 등록 페이지 비즈니스 로직

public/api/products.json, src/components/MainFeed.jsx, src/pages/MainPage.jsx, src/routes/index.tsx
- 목업 데이터를 활용해 피드 컴포넌트를 표시했습니다.
- Charkra UI를 사용해보았습니다.
- 상품명이 15글자보다 길어지면 생략되도록 했습니다.
=> feat: 기자재 조회/메인 페이지 마크업

pnpm-lock.yaml
=> fix: 차트 라이브러리 의존성  추가

src/components/Auction/AuctionPurchaseDetails.tsx, src/mocks/handlers.ts, src/routes/index.tsx
- 불필요한 formatter 함수 제거
- getSellerInformation 중복 코드 제거
- 라우팅 오류 해결
=> fix: CI/CD 오류 해결

src/hooks/AuctionForm/useAuctionForm.ts, src/hooks/ProductForm/useProductForm.ts, src/pages/AuctionFormPage.tsx, src/pages/ProductFormPage.tsx, src/utils/validator.ts
=> feat: impl form input valid, submit empty check

src/pages/AuctionFormPage.tsx
=> fix: remove duplicate form input

src/components/Auction/AuctionFeed.jsx
- 이슈 #52 참고
- 간단한 폴링 로직으로 구현
closed #52
=> feat: polling auction list

src/components/Auction/AuctionPurchase.tsx, src/components/Auction/AuctionPurchaseModal.tsx, src/hooks/Auction/useAuctionMutate.ts
- useEffect를 통해 1초마다 auction 데이터를 받아온다.
- onSucces, onError을 통해 경매 상세 페이지에서 입찰 시 중간에 입찰가가 변경될 시 오류 처리
=> feat: 경매 상세 데이터 상태 관리 및 오류 처리

src/components/Auction/AuctionFeed.jsx, src/components/Auction/AuctionPurchase.tsx
경매 쿼리데이터를 3초에 한번씩 받아오도록 수정했습니다.
=> fix: 쿼리를 3초에 한번 받아오도록 수정

src/components/Auction/AuctionPurchaseImages.tsx, src/components/Purchase/PurchaseImages.tsx
캐러샐 내의 이미지 사이즈를 고정해 깨지는 현상이 없도록 변경했습니다.
=> fix: 캐러셀 내의 이미지 크기를 고정

src/components/Main/CategorySelect.jsx
카테고리 선택 시 해당 카테고리 글자 굵기가 굵게 되도록 수정했습니다.
=> faet: 카테고리 글자 선택 시 굵기 수정

src/components/Info/Section.jsx, src/components/common/Header.tsx, src/constants/info.ts, src/pages/InfoPage.jsx, src/routes/index.tsx
- 소상공인 컨텐츠 페이지 추가
- 소상공인 컨텐츠 데이터 추가
- 컨텐츠 클릭시, 해당 링크로 이동하는 기능 추가
- header에 커뮤니티 이동 버튼 추가
=> feat: 소상공인 정보 페이지 구현

src/apis/auth.ts, src/hooks/SignUp/useSignUpForm.ts, src/pages/SignInPage.tsx, src/pages/SignUpPage.tsx
=> feat: impl check duplicated email, fix incorrect input placeholder

src/pages/SignUpPage.tsx
- hotfix refer to https://teamre-sellers.slack.com/archives/C06SHR0P62J/p1717468702833529?thread_ts=1717468515.077939&cid=C06SHR0P62J
=> fix: remove contact input value on sign up page

src/components/TransactionInformation/ProductInformation.jsx
글이 짤리는 현상을 발견해 글이 늘어남에 따라 자동으로 줄이 늘어나도록 수정했습니다.
- [#89]
=> fix: 자동 줄 늘림으로 변경

src/apis/auctions.ts, src/components/Auction/AuctionAccordionHeader.tsx, src/components/Auction/AuctionBidList.tsx, src/components/Auction/AuctionPurchase.tsx, src/components/Auction/AuctionPurchaseDetails.tsx, src/components/Auction/AuctionPurchaseModal.tsx, src/components/Auction/AuctionTime.tsx, src/components/Auction/CurrentPriceStat.tsx, src/components/Purchase/DescriptionBox.tsx
=> feat: bid list API, change auction detail UI

src/components/Delivery/DeliveryPartner.tsx, src/components/Delivery/DeliveryReview.tsx, src/components/common/Header.tsx, src/constants/delivery.ts, src/pages/DeliveryPartnerPage.tsx, src/routes/index.tsx
- 배달 제휴 페이지 추가
- 배달 제휴 목록
- 배달 리뷰 목록
- 배달 제휴 상수 추가
- 헤더에 배달 제휴 링크 추가
close #97
=> feat: 배달 제휴 페이지 추가

src/components/Auction/AuctionItem.jsx, src/components/Auction/AuctionTitle.jsx, src/components/Info/Section.jsx, src/components/Main/CategorySelect.jsx, src/components/Main/MainFeed.jsx, src/components/common/Header.tsx, src/components/common/IconTextLink.jsx, src/constants/info.ts, src/layouts/PageLayout.tsx, src/pages/AuctionListPage.jsx, src/pages/InfoPage.jsx
- 헤더 컴포넌트  
- 카테고리 컴포넌트  
- 메인 페이지  
- 경매 목록 페이지  
위 리스트들에 대해서 모바일 반응형 적용하였습니다.    
closed #86
=> feat: 헤더 컴포넌트, 카테고리 컴포넌트, 메인 페이지, 경매 목록 페이지 모바일 환경 디자인 적용

src/components/Auction/AuctionPurchase.tsx, src/components/Auction/AuctionPurchaseDetails.tsx, src/components/Auction/AuctionPurchaseImages.tsx, src/components/Auction/AuctionTime.tsx, src/components/Purchase/DescriptionBox.tsx, src/components/Purchase/Purchase.tsx, src/components/Purchase/PurchaseDetails.tsx, src/components/Purchase/PurchaseImages.tsx, src/components/TransactionInformation/ProductInformation.jsx, src/components/TransactionInformation/SellerInformation.jsx, src/pages/TransactionInformationPage.jsx
차크라 ui 에서 제공하는 스타일을 적용해 모바일 환경에 맞게 디자인을 적용했습니다.
- 작업 내용
- 구매 상세 페이지 반응형 디자인 적용
- 경매 상세 페이지 반응형 디자인 적용
- 구매 완료 페이지 반응형 디자인 적용
- 수정 필요
- 테이블 모바일 접근시 재정렬 기능
- 민준 브랜치의 헤더 수정시 변경되는 여백에 대한 코드 수정   
close - #91
=> feat: 구매 상세, 경매 입찰 페이지, 구매 완료 페이지 모바일 환경 디자인 적용

src/apis/auctions.ts, src/components/Auction/AuctionBidList.tsx, src/components/Form/FormInput.tsx, src/pages/SignInPage.tsx, src/pages/SignUpPage.tsx
closed #105 
closed #94 
- 로그인 회원가입 반응형 디자인
- 입찰 내역 목록 닉네임 -> 입찰 시간으로 수정
=> feat: 로그인/회원가입 반응형 디자인 및 api 응답값 수정

src/apis/auctions.ts, src/components/MyPage/AuctionListItem.tsx, src/components/MyPage/MyBidAuctionList.tsx, src/components/MyPage/MyBidAuctionListItem.tsx, src/components/MyPage/MyRegisteredAuctionList.tsx, src/pages/MyPage.tsx
=> feat: auction my page

src/components/MyPage/MyBidAuctionListItem.tsx
=> fix: replace wrong text

src/components/Main/CategorySelect.jsx, src/components/common/Header.tsx
closed #116 
xl사이즈 일 때는 navbar가 보이도록 하고, lg부터는 base까지는 navbar 영역이 부족해서 햄버거 메뉴로 대체했습니다.
xl사이즈가 아닐 때 햄버거 메뉴를 열었다가, xl사이즈가 되더라도 Drawer가 남아있는 문제가 있었습니다. xl사이즈가 되면 자동으로 Drawer가 닫히도록 했습니다.
=> feat: 특정 viewport에서 navbar 디자인 깨지는 문제 해결

src/apis/auctions.ts, src/components/Auction/AuctionPurchase.tsx, src/components/Auction/AuctionPurchaseDetails.tsx, src/components/Auction/AuctionPurchaseModal.tsx
- 첫번째 에러처리 : 입찰가가 현재 입찰가보다 같거나 적을 때
- 두번째 에러처리 : 판매자가 구매자와 같은 id를 갖고 있을 때
close #115
=> fix: 자기자신이 올린 물품을 입찰 할 시 에러문구가 모호함
